import type { Book, UserBookOwnership } from "@/schemas/book.schema";
import type { BookFormErrors, BookFormFields } from "@/types/bookForm";
import { toSlug, uniqueSlug } from "@/utils/slug";
import type { Library, Series } from "@/schemas/library.schema";

// These helpers were adapted from code generated by Claude

export function bookToFields(book: Book | null): BookFormFields {
  if (!book) {
    return {
      title: "",
      author: "",
      isbn: "",
      coverPreviewUrl: null,
      coverImage: null,
      publishedDate: "",
      ownershipKind: "wishlist",
      ownershipPlatform: "",
      notes: "",
      genreIds: [],
      seriesId: "",
      seriesOrder: "",
      seriesNewName: "",
      readthroughs: [],
    };
  }

  return {
    title: book.title,
    author: book.author,
    isbn: book.isbn ?? "",
    coverPreviewUrl: null,
    coverImage: null,
    publishedDate: book.publishedDate
      ? book.publishedDate.toISOString().slice(0, 10)
      : "",
    ownershipKind: book.userData.ownership.kind,
    ownershipPlatform:
      book.userData.ownership.kind === "digital"
        ? book.userData.ownership.platform
        : "",
    notes: book.userData.notes ?? "",
    genreIds: book.genreIds,
    seriesId: book.kind === "series" ? book.seriesId : "",
    seriesOrder: book.kind === "series" ? String(book.seriesOrder) : "",
    seriesNewName: "",
    readthroughs:
      book.userData.readthroughs?.map((r) => ({
        finishedAt: r.finishedAt.toISOString().slice(0, 10),
        rating: r.rating != null ? String(r.rating) : "",
        notes: r.notes ?? "",
      })) ?? [],
  };
}

export function fieldsToBook(
  original: Book | null,
  fields: BookFormFields,
  library: Library,
): { book: Book; newSeries: Series | null } {
  const existingBookIds = new Set(library.books.map((b) => b.id));
  const existingSeriesIds = new Set(library.series.map((s) => s.id));

  const id = original
    ? original.id
    : uniqueSlug(toSlug(fields.title), existingBookIds);

  const ownership: UserBookOwnership =
    fields.ownershipKind === "digital"
      ? { kind: "digital", platform: fields.ownershipPlatform.trim() }
      : { kind: fields.ownershipKind };

  const base = {
    id,
    title: fields.title.trim(),
    author: fields.author.trim(),
    isbn: fields.isbn.trim() || undefined,
    publishedDate: fields.publishedDate
      ? new Date(fields.publishedDate)
      : undefined,
    genreIds: fields.genreIds,
    userData: {
      ...(original?.userData ?? {}),
      ownership,
      notes: fields.notes.trim() || undefined,
      readthroughs: fields.readthroughs
        .filter((r) => r.finishedAt)
        .map((r) => ({
          finishedAt: new Date(r.finishedAt),
          rating: r.rating ? Number(r.rating) : undefined,
          notes: r.notes.trim() || undefined,
        })),
    },
  };

  const rawSeriesId = fields.seriesId.trim();

  if (!rawSeriesId) {
    return { book: { ...base, kind: "standalone" }, newSeries: null };
  }

  if (rawSeriesId === "_new") {
    const newSeriesId = uniqueSlug(
      toSlug(fields.seriesNewName),
      existingSeriesIds,
    );
    return {
      book: {
        ...base,
        kind: "series",
        seriesId: newSeriesId,
        seriesOrder: Number(fields.seriesOrder) || 0,
      },
      newSeries: { id: newSeriesId, name: fields.seriesNewName.trim() },
    };
  }

  return {
    book: {
      ...base,
      kind: "series",
      seriesId: rawSeriesId,
      seriesOrder: Number(fields.seriesOrder) || 0,
    },
    newSeries: null,
  };
}

export function validate(fields: BookFormFields): BookFormErrors {
  const errors: BookFormErrors = {};

  if (!fields.title.trim()) {
    errors.title = "Title is required.";
  }

  if (!fields.author.trim()) {
    errors.author = "Author is required.";
  }

  if (
    fields.isbn &&
    !/^\d{9}[\dX]$|^\d{13}$/.test(fields.isbn.replace(/-/g, ""))
  ) {
    errors.isbn = "ISBN must be a valid 10- or 13-digit number.";
  }

  if (fields.publishedDate && isNaN(Date.parse(fields.publishedDate))) {
    errors.publishedDate = "Published date is not a valid date.";
  }

  if (fields.ownershipKind === "digital" && !fields.ownershipPlatform.trim()) {
    errors.ownershipPlatform = "Platform is required for digital books.";
  }

  if (fields.seriesId === "_new" && !fields.seriesNewName.trim()) {
    errors.seriesNewName = "Series name is required.";
  }

  if (fields.seriesId && !fields.seriesOrder.trim()) {
    errors.seriesOrder = "Order in series is required.";
  } else if (fields.seriesOrder.trim() && isNaN(Number(fields.seriesOrder))) {
    errors.seriesOrder = "Series order must be a number.";
  }

  const readthroughErrors = fields.readthroughs.map((r) => {
    if (r.finishedAt && isNaN(Date.parse(r.finishedAt))) {
      return "Finished date is not a valid date.";
    }
    if (
      r.rating &&
      (isNaN(Number(r.rating)) || Number(r.rating) < 1 || Number(r.rating) > 5)
    ) {
      return "Rating must be a number between 1 and 5.";
    }
    return "";
  });

  if (readthroughErrors.some(Boolean)) {
    errors.readthroughs = readthroughErrors;
  }

  return errors;
}
