import { string } from "zod";
import { useBookCover } from "../hooks/useBookCover";
import type { Book } from "../schemas/book.schema";
import type { BookFormErrors, BookFormFields } from "../types/BookForm";

// These helpers were adapted from code generated by Claude

export function bookToFields(book: Book | null): BookFormFields {
  if (!book) {
    return {
      title: "",
      author: "",
      isbn: "",
      coverPreviewUrl: null,
      coverImage: null,
      publishedDate: "",
      ownershipKind: "unowned",
      ownershipPlatform: "",
      notes: "",
      genreIds: [],
      seriesId: "",
      seriesOrder: "",
      seriesNewName: "",
    };
  }

  const existingCoverUrl = useBookCover(book?.id ?? "");

  return {
    title: book.title,
    author: book.author,
    isbn: book.isbn ?? "",
    coverPreviewUrl: existingCoverUrl,
    coverImage: null,
    publishedDate: book.publishedDate
      ? book.publishedDate.toISOString().slice(0, 10)
      : "",
    ownershipKind: book.userData.ownership.kind,
    ownershipPlatform:
      book.userData.ownership.kind === "digital"
        ? book.userData.ownership.platform
        : "",
    notes: book.userData.notes ?? "",
    genreIds: book.genreIds,
    seriesId: book.kind === "series" ? book.seriesId : "",
    seriesOrder: book.kind === "series" ? String(book.seriesOrder) : "",
    seriesNewName: "",
  };
}

export function fieldsToBook(original: Book, fields: BookFormFields): Book {
  const ownership =
    fields.ownershipKind === "digital"
      ? { kind: "digital" as const, platform: fields.ownershipPlatform.trim() }
      : { kind: fields.ownershipKind as "unowned" | "physical" };

  const base = {
    ...original,
    title: fields.title.trim(),
    author: fields.author.trim(),
    isbn: fields.isbn.trim() || undefined,
    publishedDate: fields.publishedDate
      ? new Date(fields.publishedDate)
      : undefined,
    genreIds: fields.genreIds,
    userData: {
      ...original.userData,
      ownership,
      notes: fields.notes.trim() || undefined,
    },
  };

  if (fields.seriesId.trim()) {
    return {
      ...base,
      kind: "series",
      seriesId: fields.seriesId.trim(),
      seriesOrder: Number(fields.seriesOrder) || 0,
    };
  }

  return { ...base, kind: "standalone" };
}

export function validate(fields: BookFormFields): BookFormErrors {
  const errors: BookFormErrors = {};

  if (!fields.title.trim()) {
    errors.title = "Title is required.";
  }

  if (!fields.author.trim()) {
    errors.author = "Author is required.";
  }

  if (
    fields.isbn &&
    !/^\d{9}[\dX]$|^\d{13}$/.test(fields.isbn.replace(/-/g, ""))
  ) {
    errors.isbn = "ISBN must be a valid 10- or 13-digit number.";
  }

  if (fields.publishedDate && isNaN(Date.parse(fields.publishedDate))) {
    errors.publishedDate = "Published date is not a valid date.";
  }

  if (fields.ownershipKind === "digital" && !fields.ownershipPlatform.trim()) {
    errors.ownershipPlatform = "Platform is required for digital books.";
  }

  if (fields.seriesId === "_new" && !fields.seriesNewName.trim()) {
    errors.seriesNewName = "Series name is required.";
  }

  if (fields.seriesId && !fields.seriesOrder.trim()) {
    errors.seriesOrder = "Order in series is required.";
  } else if (fields.seriesOrder.trim() && isNaN(Number(fields.seriesOrder))) {
    errors.seriesOrder = "Series order must be a number.";
  }

  return errors;
}
